reorganisation

diff --git a/run_onchange_after_addons.bash.tmpl b/run_onchange_after_addons.bash.tmpl
--- a/run_onchange_after_addons.bash.tmpl
+++ b/run_onchange_after_addons.bash.tmpl
@@ -1,8 +1,10 @@
 #!/bin/bash
 
+# This installs lua libs and various scripts
+
 set -e
 
-VERSION="20260324-0"
+VERSION="20260728-0"
 
 # To force a trigger of this file, even if no changes have 
 # occured, increment this:
@@ -25,9 +27,13 @@ LUALIBS[lee]="{{ include "lua/lee.lua" | sha256sum }}"
 LUALIBS[tmpl]="{{ include "lua/tmpl.lua" | sha256sum }}"
 
 declare -A LUASCRIPTS
-LUASCRIPTS[ghbin]="{{ include "lua/ghbin" | sha256sum }}"
-LUASCRIPTS[vigilax]="{{ include "lua/vigilax" | sha256sum }}"
-LUASCRIPTS[lod]="{{ include "lua/lod" | sha256sum }}"
+LUASCRIPTS[ghbin]="{{ include "scripts/ghbin" | sha256sum }}"
+LUASCRIPTS[vigilax]="{{ include "scripts/vigilax" | sha256sum }}"
+LUASCRIPTS[lod]="{{ include "scripts/lod" | sha256sum }}"
+
+declare -A WGSCRIPTS
+WGSCRIPTS[wg-json]="{{ include "scripts/wg-json" | sha256sum }}"
+WGSCRIPTS[wg-status]="{{ include "scripts/wg-status" | sha256sum }}"
 
 main() {
 	echo -e "\e[34m[LUA Libs And Scripts]\e[m"
@@ -36,7 +42,10 @@ main() {
 		return
 	}
 	deploy_libs
-	deploy_scripts
+	deploy_luascripts
+	which wg >/dev/null 2>&1 && {
+		deploy_wgscripts
+	}
 }
 
 deploy_libs() {
@@ -53,13 +62,26 @@ deploy_libs() {
 	done
 }
 
-deploy_scripts() {
+deploy_luascripts() {
+	echo -e "\e[34m[Lua Scripts]\e[m"
 	for luascript in "${!LUASCRIPTS[@]}"; do
 		sudo install --compare -D --target "/usr/local/bin" --mode 0755 \
-		"{{ joinPath .chezmoi.sourceDir "lua/${luascript}" | quote }}" && {
+		"{{ joinPath .chezmoi.sourceDir "scripts/${luascript}" | quote }}" && {
 			echo -e "\e[1;32mOK\e[m ${luascript}"
 		} || {
 			echo -e "\e[1;31mFAIL!\e[m ${luascript}"
+		}
+	done
+}
+
+deploy_wgscripts() {
+	echo -e "\e[34m[WireGuard Scripts]\e[m"
+	for wgscript in "${!WGSCRIPTS[@]}"; do
+		sudo install --compare -D --target "/usr/local/bin" --mode 0755 \
+		"{{ joinPath .chezmoi.sourceDir "scripts/${wgscript}" | quote }}" && {
+			echo -e "\e[1;32mOK\e[m ${script}"
+		} || {
+			echo -e "\e[1;31mFAIL!\e[m ${script}"
 		}
 	done
 }
